/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface GpExitIntent {
        "buttonLabel": string;
        "caption": string;
        "checkboxLabel": string;
        "description": string;
        "downloadDocName": string;
        "downloadDocSrc": string;
        "imageSrcDesktop": string;
        "imageSrcMobile": string;
    }
}
declare global {
    interface HTMLGpExitIntentElement extends Components.GpExitIntent, HTMLStencilElement {
    }
    var HTMLGpExitIntentElement: {
        prototype: HTMLGpExitIntentElement;
        new (): HTMLGpExitIntentElement;
    };
    interface HTMLElementTagNameMap {
        "gp-exit-intent": HTMLGpExitIntentElement;
    }
}
declare namespace LocalJSX {
    interface GpExitIntent {
        "buttonLabel"?: string;
        "caption"?: string;
        "checkboxLabel"?: string;
        "description"?: string;
        "downloadDocName"?: string;
        "downloadDocSrc"?: string;
        "imageSrcDesktop"?: string;
        "imageSrcMobile"?: string;
    }
    interface IntrinsicElements {
        "gp-exit-intent": GpExitIntent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gp-exit-intent": LocalJSX.GpExitIntent & JSXBase.HTMLAttributes<HTMLGpExitIntentElement>;
        }
    }
}
